### ISSUE TITLE
Erstes Release erstellen und im Installer veröffentlichen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/treestructure#2]
Der Installer scheint inzwischen so populär geworden zu sein, dass man das Gefühl bekommt, es wird quasi ausschließlich nur noch beachtet, was im Installer vorhanden ist. Addons, die nur bei Github liegen oder durchs Forum fliegen, werden kaum beachtet.

Insofern: Ein erstes (Beta-)Release wäre sinnvoll :)

**Comment by staabm** [comment]
:+1:

**Comment by skerbis** [comment]
Hier passiert wohl nichts mehr?

**Comment by schuer** [comment]
@tgoellner arbeitet nicht mehr mit REDAXO, deshalb passiert hier (und auch bei bloecks und Co.) nur noch etwas, wenn jemand anderes aktiv wird.
