### ISSUE TITLE
Info für Developer ergänzen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/treestructure#3]
Der Frontend-Workflow (Grunt, LESS und Bimmelbam) sollte zumindest grob erklärt werden, damit andere Devs die Addon-Entwicklung unterstützen können.

**Comment by staabm** [comment]
ich denke nicht dass man diesen hier in einem anderen addon beschreiben sollte, aber man könnte an eine zentrale stelle verweisen wo es erklärt wird (ansonsten beschreiben wir das gleiche in allen addons)
