### ISSUE TITLE
Shell-Skripte entfernen?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/treestructure#4]
oder werden die benötigt?

**Comment by skerbis** [comment]
ping

**Comment by schuer** [comment]
Stolpere gerade zufällig drüber. Die Shell-Skripte werden benötigt und sind sehr praktisch. Habe bei BlÖcks damit zu tun gehabt, Thomas hat sie damals wohl in allen seiner AddOns verwendet.
